name: 01 - Building Blocks

on: workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Success step
        run: |
          echo "I'm working and ended with success!"
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye"