name: 05 - 2 - Event Filters and Activity Types

on: 
    pull_request:
        types: [closed]
        branches: main

jobs:
    Printer:
        runs-on: ubuntu-latest
        steps:
            - name: Printing
            run: echo "Running whenever a PR is closed"
