name: 07 - Using expressions
run-name: 07 - Using expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF'}}

on:
  push:
  workflow_dispatch:
    inputs: 
      debug:
        type: boolean
        default: false

jobs:
  ECHO:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug }}
        run: |
            echo "Triggered by: ${{ github.event }}"
            echo "Branch: ${{ github.ref }}"
            echo "Commit SHA: ${{ github.sha }}"
            echo "Unner OS: ${{ runner.os }}"
      - name: "[debug] Print when triggered from main"
        if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
        run: echo "I was triggered from main"